### ISSUE TITLE
[QUESTION] How did you generate Canvas.txt? 

### ISSUE THREAD

**Issue by Rob-Rychs** [CHEF-KOCH/Canvas-fingerprinting-pages#1]
Hi! I'm curious about how you generated the Canvas.txt file? 
So to appropriately use this data you would just blacklist all those domains either at the browser preferences level or through a browser extension? 
Thanks for your time boss

**Comment by CHEF-KOCH** [comment]
It's not generated it's pure handwork and the reason why I only release an update once in a year.
