### ISSUE TITLE
Legit website blocked

### ISSUE THREAD

**Issue by anudeepND** [CHEF-KOCH/Canvas-fingerprinting-pages#2]
Hi,
`0.0.0.0 bethesda.net`
is blocked by your host file. Bethesda is a legit gaming company - https://en.wikipedia.org/wiki/Bethesda_Softworks
Please remove it

**Comment by CHEF-KOCH** [comment]
Because it uses canvas fingerprinting techniques e.g. to bypass adblockers and to track you.
